### ISSUE TITLE
ImportError: cannot import name 'new_thread'

### ISSUE THREAD

**Issue by masbodo** [lzzy12/python-aria-mirror-bot#122]
i got this error .. how to fix ?? thanks

```
2020-06-29T11:58:25.684623+00:00 app[worker.1]: 2020-06-29 11:58:25,684 - pyrogram.crypto.aes - INFO - Using TgCrypto
2020-06-29T11:58:26.081193+00:00 app[worker.1]: Traceback (most recent call last):
2020-06-29T11:58:26.081267+00:00 app[worker.1]:   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
2020-06-29T11:58:26.081268+00:00 app[worker.1]:     "__main__", mod_spec)
2020-06-29T11:58:26.081268+00:00 app[worker.1]:   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
2020-06-29T11:58:26.081269+00:00 app[worker.1]:     exec(code, run_globals)
2020-06-29T11:58:26.081269+00:00 app[worker.1]:   File "/usr/src/app/bot/__main__.py", line 15, in <module>
2020-06-29T11:58:26.081269+00:00 app[worker.1]:     from .modules import authorize, list, cancel_mirror, mirror_status, mirror, clone, watch
2020-06-29T11:58:26.081270+00:00 app[worker.1]:   File "/usr/src/app/bot/modules/clone.py", line 6, in <module>
2020-06-29T11:58:26.081270+00:00 app[worker.1]:     from bot.helper.ext_utils.bot_utils import new_thread
2020-06-29T11:58:26.081270+00:00 app[worker.1]: ImportError: cannot import name 'new_thread'
2020-06-29T11:58:26.263213+00:00 heroku[worker.1]: Process exited with status 1
2020-06-29T11:58:26.295646+00:00 heroku[worker.1]: State changed from up to crashed
```

**Comment by WiizarDxD** [comment]
@masbodo Heroku not supported

**Comment by iamlordutkarsh** [comment]
@masbodo Heroku 😂

**Comment by jaskaranSM** [comment]
Closing this, as the platform you are using is no longer supported.

**Comment by masbodo** [comment]
> @masbodo Heroku not supported

its working for me ... before update (version 3.0)

**Comment by iamlordutkarsh** [comment]
Now heroku support is removed !
