### ISSUE TITLE
Deploy succeeded but sending files to mirror causes the following

### ISSUE THREAD

**Issue by jamesjamesa** [lzzy12/python-aria-mirror-bot#15]
`Exception in thread Thread-1:
 Traceback (most recent call last):
 File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn
 conn = connection.create_connection(
 File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
 raise err
 File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
 sock.connect(sa)
 ConnectionRefusedError: [Errno 111] Connection refused

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
 File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
 httplib_response = self._make_request(
 File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
 conn.request(method, url, **httplib_request_kw)
 File "/usr/local/lib/python3.8/http/client.py", line 1230, in request
 self._send_request(method, url, body, headers, encode_chunked)
 File "/usr/local/lib/python3.8/http/client.py", line 1276, in _send_request
 self.endheaders(body, encode_chunked=encode_chunked)
 File "/usr/local/lib/python3.8/http/client.py", line 1225, in endheaders
 self._send_output(message_body, encode_chunked=encode_chunked)
 File "/usr/local/lib/python3.8/http/client.py", line 1004, in _send_output
 self.send(msg)
 File "/usr/local/lib/python3.8/http/client.py", line 944, in send
 self.connect()
 File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 184, in connect
 conn = self._new_conn()
 File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 168, in _new_conn
 raise NewConnectionError(
 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f2b9ec73df0>: Failed to establish a new connection: [Errno 111] Connection refused

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
 File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
 resp = conn.urlopen(
 File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
 retries = retries.increment(
 File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
 raise MaxRetryError(_pool, url, error or ResponseError(cause))
 urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2b9ec73df0>: Failed to establish a new connection: [Errno 111] Connection refused'))

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
 File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
 self.run()
 File "/usr/local/lib/python3.8/threading.py", line 870, in run
 self._target(*self._args, **self._kwargs)
 File "/usr/src/app/bot/helper/mirror_utils/download_tools.py", line 21, in add_download
 download = aria2.add_uris([link], {'dir': DOWNLOAD_DIR + str(self.__listener.uid)})
 File "/usr/local/lib/python3.8/site-packages/aria2p/api.py", line 154, in add_uris
 gid = self.client.add_uri(uris, client_options, position)
 File "/usr/local/lib/python3.8/site-packages/aria2p/client.py", line 441, in add_uri
 return self.call(self.ADD_URI, params=[uris, options, position])
 File "/usr/local/lib/python3.8/site-packages/aria2p/client.py", line 224, in call
 return self.res_or_raise(self.post(self.get_payload(method, params, msg_id=msg_id)))
 File "/usr/local/lib/python3.8/site-packages/aria2p/client.py", line 321, in post
 return requests.post(self.server, data=payload).json()
 File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 116, in post
 return request('post', url, data=data, json=json, **kwargs)
 File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 60, in request
 return session.request(method=method, url=url, **kwargs)
 File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
 resp = self.send(prep, **send_kwargs)
 File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
 r = adapter.send(request, **kwargs)
 File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
 raise ConnectionError(e, request=request)
 requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2b9ec73df0>: Failed to establish a new connection: [Errno 111] Connection refused'))`

**Comment by jamesmoltres** [comment]
followed all steps from https://github.com/lzzy12/python-aria-mirror-bot#deploying-on-heroku

**Comment by lzzy12** [comment]
Try doing chmod +x aria.sh 
Then git commit and push it to heroku again

**Comment by jamesjamesa** [comment]
I used windows to push it, cant chmod.

**Comment by jamesjamesa** [comment]
Tested with fresh deploy on different port, same issue

**Comment by lzzy12** [comment]
https://github.com/lzzy12/python-aria-mirror-bot/commit/f11e9a206cd9763325fe5b46ed725467d3e52271

**Comment by jamesjamesa** [comment]
Still same 

requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81dee70b20>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by jamesjamesa** [comment]
nvm, works now

**Comment by thegreatestminer** [comment]
I get a connection refused error while deploying, and the dockerfile *does* have `RUN chmod +x aria.sh` in it....
