### ISSUE TITLE
 Error in the latest code

### ISSUE THREAD

**Issue by fzsimlu** [lzzy12/python-aria-mirror-bot#158]
Just now, an error occurred after the download code was compiled。
system: CentOS Linux release 7.8.2003
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 6, in <module>
    import aria2p
  File "/usr/local/lib/python3.6/dist-packages/aria2p/__init__.py", line 9, in <module>
    from loguru import logger
  File "/usr/local/lib/python3.6/dist-packages/loguru/__init__.py", line 10, in <module>
    from ._logger import Core as _Core
  File "/usr/local/lib/python3.6/dist-packages/loguru/_logger.py", line 109, in <module>
    from aiocontextvars import ContextVar
  File "/usr/local/lib/python3.6/dist-packages/aiocontextvars.py", line 9, in <module>
    from contextvars import Context, ContextVar, Token, copy_context
ModuleNotFoundError: No module named 'contextvars'
[root@testaria2 mirror-bot]# git pull
Already up-to-date.
```

**Comment by iamlordutkarsh** [comment]
@fzsimlu U deployed on heroku ig 😐

**Comment by fzsimlu** [comment]
Can't run on centos docker?

**Comment by ParveenBhadooOfficial** [comment]
everyone getting this.

**Comment by fzsimlu** [comment]
Just a few days ago, it was running normally in centos docker.
