### ISSUE TITLE
YouTube-DL fell

### ISSUE THREAD

**Issue by OryWareKyrie** [lzzy12/python-aria-mirror-bot#176]
recently the YouTube-DL repository has been disabled, although there is a backup on gitlab. but I'm getting this error.

```
2020-10-25T18:22:01.066869+00:00 app[worker.1]: bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
2020-10-25T18:22:01.068065+00:00 app[worker.1]: bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
2020-10-25T18:22:03.328516+00:00 app[worker.1]: 2020-10-25 18:22:03,328 - pyrogram.crypto.aes - INFO - Using TgCrypto
2020-10-25T18:22:03.466071+00:00 app[worker.1]: Traceback (most recent call last):
2020-10-25T18:22:03.466073+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2020-10-25T18:22:03.466074+00:00 app[worker.1]:     return _run_code(code, main_globals, None,
2020-10-25T18:22:03.466074+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
2020-10-25T18:22:03.466080+00:00 app[worker.1]:     exec(code, run_globals)
2020-10-25T18:22:03.466081+00:00 app[worker.1]:   File "/usr/src/app/bot/__main__.py", line 16, in <module>
2020-10-25T18:22:03.466083+00:00 app[worker.1]:     from .modules import authorize, list, cancel_mirror, mirror_status, mirror, clone, watch
2020-10-25T18:22:03.466083+00:00 app[worker.1]:   File "/usr/src/app/bot/modules/watch.py", line 7, in <module>
2020-10-25T18:22:03.466084+00:00 app[worker.1]:     from bot.helper.mirror_utils.download_utils.youtube_dl_download_helper import YoutubeDLHelper
2020-10-25T18:22:03.466084+00:00 app[worker.1]:   File "/usr/src/app/bot/helper/mirror_utils/download_utils/youtube_dl_download_helper.py", line 3, in <module>
2020-10-25T18:22:03.466085+00:00 app[worker.1]:     from youtube_dl import YoutubeDL, DownloadError
2020-10-25T18:22:03.466085+00:00 app[worker.1]: ModuleNotFoundError: No module named 'youtube_dl'
```

**Comment by tldr-cell** [comment]
Tbh, unsupported platform

**Comment by viper-adnan** [comment]
> Tbh, unsupported platform

He is not asking about [heroku](https://heroku.com). It's a problem which is occurring due to the repo. You will help him If he run the same code on his local server ?

**Comment by lzzy12** [comment]
It will be fixed soon

**Comment by OryWareKyrie** [comment]
> It will be fixed soon

Thanks
