### ISSUE TITLE
telegram files not downloading :(

### ISSUE THREAD

**Issue by AmirulAndalib** [lzzy12/python-aria-mirror-bot#189]
2020-12-04T05:08:40.745128+00:00 app[worker.1]: 2020-12-04 05:08:40,744 - pyrogram.crypto.aes - INFO - Using TgCrypto
2020-12-04T05:08:41.862418+00:00 app[worker.1]: 2020-12-04 05:08:41,862 - bot - INFO - Bot Started!
2020-12-04T05:08:54.909780+00:00 app[worker.1]: 2020-12-04 05:08:54,909 - bot - INFO - 
2020-12-04T05:08:54.912387+00:00 app[worker.1]: 2020-12-04 05:08:54,910 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
2020-12-04T05:08:54.912388+00:00 app[worker.1]: Traceback (most recent call last):
2020-12-04T05:08:54.912389+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/telegram/utils/promise.py", line 57, in run
2020-12-04T05:08:54.912390+00:00 app[worker.1]:     self._result = self.pooled_function(*self.args, **self.kwargs)
2020-12-04T05:08:54.912390+00:00 app[worker.1]:   File "/usr/src/app/bot/modules/mirror.py", line 223, in mirror
2020-12-04T05:08:54.912393+00:00 app[worker.1]:     _mirror(context.bot, update)
2020-12-04T05:08:54.912394+00:00 app[worker.1]:   File "/usr/src/app/bot/modules/mirror.py", line 195, in _mirror
2020-12-04T05:08:54.912395+00:00 app[worker.1]:     tg_downloader = TelegramDownloadHelper(listener)
2020-12-04T05:08:54.912395+00:00 app[worker.1]:   File "/usr/src/app/bot/helper/mirror_utils/download_utils/telegram_downloader.py", line 29, in __init__
2020-12-04T05:08:54.912396+00:00 app[worker.1]:     self.__user_bot.start()
2020-12-04T05:08:54.912396+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/client/client.py", line 825, in start
2020-12-04T05:08:54.912397+00:00 app[worker.1]:     is_authorized = self.connect()
2020-12-04T05:08:54.912398+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/client/client.py", line 260, in connect
2020-12-04T05:08:54.912398+00:00 app[worker.1]:     self.load_config()
2020-12-04T05:08:54.912398+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/client/client.py", line 1390, in load_config
2020-12-04T05:08:54.912399+00:00 app[worker.1]:     parser.read(str(self.config_file))
2020-12-04T05:08:54.912399+00:00 app[worker.1]:   File "/usr/lib/python3.8/configparser.py", line 697, in read
2020-12-04T05:08:54.912399+00:00 app[worker.1]:     self._read(fp, filename)
2020-12-04T05:08:54.912400+00:00 app[worker.1]:   File "/usr/lib/python3.8/configparser.py", line 1082, in _read
2020-12-04T05:08:54.912400+00:00 app[worker.1]:     raise MissingSectionHeaderError(fpname, lineno, line)
2020-12-04T05:08:54.912401+00:00 app[worker.1]: configparser.MissingSectionHeaderError: File contains no section headers.
2020-12-04T05:08:54.912401+00:00 app[worker.1]: file: '/usr/src/app/bot/config.ini', line: 2
2020-12-04T05:08:54.912401+00:00 app[worker.1]: 'BOT_TOKEN = "1498350168:AAHPgo2bwwYcmJEzty9HRZ3TgykPCGsRHZo"\n'

i have given the bot all admin privilges
bot is authorized
i used bot token for string

what can be done to solve this?

**Comment by AmirulAndalib** [comment]
but i deployed on heroku with a new turotial please help

**Comment by AmirulAndalib** [comment]
i even mirrroed torrents

**Comment by AmirulAndalib** [comment]
it wont ban just help me fix
