### ISSUE TITLE
help me please.

### ISSUE THREAD

**Issue by doloresjose** [lzzy12/python-aria-mirror-bot#199]
i am getting this error after successful deployments

bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
2021-01-04T11:51:03.829325+00:00 app[worker.1]: bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
2021-01-04T11:51:04.571287+00:00 app[worker.1]: 2021-01-04 11:51:04,570 - root - WARNING - MEGA Credentials not provided!
2021-01-04T11:51:04.914560+00:00 app[worker.1]: Traceback (most recent call last):
2021-01-04T11:51:04.914614+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2021-01-04T11:51:04.914615+00:00 app[worker.1]:     return _run_code(code, main_globals, None,
2021-01-04T11:51:04.914616+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
2021-01-04T11:51:04.914617+00:00 app[worker.1]:     exec(code, run_globals)
2021-01-04T11:51:04.914618+00:00 app[worker.1]:   File "/usr/src/app/bot/__main__.py", line 16, in <module>
2021-01-04T11:51:04.914627+00:00 app[worker.1]:     from .modules import authorize, list, cancel_mirror, mirror_status, mirror, clone, watch, delete
2021-01-04T11:51:04.914628+00:00 app[worker.1]:   File "/usr/src/app/bot/modules/list.py", line 2, in <module>
2021-01-04T11:51:04.914628+00:00 app[worker.1]:     from bot.helper.mirror_utils.upload_utils.gdriveTools import GoogleDriveHelper
2021-01-04T11:51:04.914629+00:00 app[worker.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 24, in <module>
2021-01-04T11:51:04.914629+00:00 app[worker.1]:     from bot import parent_id, DOWNLOAD_DIR, IS_TEAM_DRIVE, INDEX_URL, \
2021-01-04T11:51:04.914630+00:00 app[worker.1]: ImportError: cannot import name 'CRED_JSON' from 'bot' (/usr/src/app/bot/__init__.py)

please tell me what is this error  ImportError: cannot import name 'CRED_JSON' from 'bot'

**Comment by jaskaranSM** [comment]
Totally unsupported platform

**Comment by doloresjose** [comment]
ok, but can you tell me whtas the reason for this "ImportError: cannot import name 'CRED_JSON' from 'bot'" error
