### ISSUE TITLE
Add a deploy to heroku button

### ISSUE THREAD

**Issue by Towha** [lzzy12/python-aria-mirror-bot#21]
I am on android and for some fucking reason getting this error code :
Traceback (most recent call last):
  File "generate_drive_token.py", line 16, in <module>
    flow = InstalledAppFlow.from_client_secrets_file(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/google_auth_oauthlib/flow.py", line 180, in from_client_secrets_file
    with open(client_secrets_file, 'r') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'
$

so my suggestion is to add deploy to heroku button please do it! and then this bot will be much easier to make/deploy

**Comment by a092devs** [comment]
@Towha Add credentials.json to the root directory before running the generate_drive_token.py

**Comment by Towha** [comment]
what are we gonna use after heroku is dead?🤔

**Comment by a092devs** [comment]
@Towha Use VPS.
Did you resolve your issue though?
