### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by arjun4414** [lzzy12/python-aria-mirror-bot#23]
~/mirror-bot$ python3 generate_drive_token.py
Traceback (most recent call last):
  File "generate_drive_token.py", line 3, in <module>
    from google_auth_oauthlib.flow import InstalledAppFlow
ModuleNotFoundError: No module named 'google_auth_oauthlib'

**Comment by arjun4414** [comment]
i am getting this error

**Comment by arjun4414** [comment]
can you help me with this ??

**Comment by lzzy12** [comment]
Read readme file carefully

Do pip3 install google-api-python-client google-auth-httplib2 google-auth-oauthlib

**Comment by arjun4414** [comment]
done but still same error

**Comment by arjun4414** [comment]
/mirror-bot$ python3 generate_drive_token.py
Traceback (most recent call last):
  File "generate_drive_token.py", line 17, in <module>
    'credentials.json', __OAUTH_SCOPE)
  File "/home/upadhyayarjun7/.local/lib/python3.7/site-packages/google_auth_oauthlib/flow.py", line 197, in from_client_secrets_file
    client_config = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by a092devs** [comment]
@arjun4414 check your credentials.json file that it is in proper format

**Comment by arjun4414** [comment]
Traceback (most recent call last):
  File "generate_drive_token.py", line 17, in <module>
    'credentials.json', __OAUTH_SCOPE)
  File "/home/upadhyayarjun7/.local/lib/python3.7/site-packages/google_auth_oauthlib/flow.py", line 197, in from_client_secrets_file
    client_config = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)



this is the error downloaded new file and replaced the file but same error can you please help me !!

**Comment by arjun4414** [comment]
if you say i will send my file to you for cross  checking
