### ISSUE TITLE
Error in deploy (One or more env variables missing!)

### ISSUE THREAD

**Issue by morning3tar** [lzzy12/python-aria-mirror-bot#234]
Hi, I deployed from master branch and got these errors :

> 2021-05-12 15:17:10,062 - bot - ERROR - One or more env variables missing! Exiting now
Exception ignored in: <function ClientSession.__del__ at 0x7f3b48bf3430>
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 337, in __del__
File "/usr/lib/python3.8/asyncio/base_events.py", line 1740, in call_exception_handler
File "/usr/lib/python3.8/logging/__init__.py", line 1463, in error
File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log
File "/usr/lib/python3.8/logging/__init__.py", line 1587, in handle
File "/usr/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
File "/usr/lib/python3.8/logging/__init__.py", line 950, in handle
File "/usr/lib/python3.8/logging/__init__.py", line 1182, in emit
File "/usr/lib/python3.8/logging/__init__.py", line 1172, in _open
NameError: name 'open' is not defined

**Comment by sysgrammer** [comment]
Hi I think this is due leaving an empty environment variable. I was able to reproduce this as well. You must have left USE_SERVICE_ACCOUNTS variable empty... atleast I did. You can solve this by setting it "False"
