### ISSUE TITLE
help

### ISSUE THREAD

**Issue by fabriciosc123pro** [lzzy12/python-aria-mirror-bot#240]
Traceback (most recent call last):
  File "gen_sa_accounts.py", line 337, in <module>
    resp = serviceaccountfactory(
  File "gen_sa_accounts.py", line 196, in serviceaccountfactory
    cloud = build('cloudresourcemanager', 'v1', credentials=creds)
  File "/home/fabriciosc/.local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/fabriciosc/.local/lib/python3.8/site-packages/googleapiclient/discovery.py", line 321, in build
    discovery_http.close()
AttributeError: 'Http' object has no attribute 'close'

**Comment by abdiasriver** [comment]
Put credentials.json on the proyect 

Create google accounts here
https://github.com/abdiasriver/CuentasGooglegroups
