### ISSUE TITLE
soxket issue

### ISSUE THREAD

**Issue by mohitjoshi155** [lzzy12/python-aria-mirror-bot#261]
2022/05/29 17:19:47 No mega.nz api key provided, exiting.
2022-05-29 17:19:50,961 - bot - INFO - Mega API KEY provided but credentials not provided. Starting mega in anonymous mode!
2022-05-29 17:19:51,291 - pyrogram.crypto.aes - INFO - Using TgCrypto
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/aria2p/client.py", line 1723, in listen_to_notifications
    socket = websocket.create_connection(ws_server, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/websocket/_core.py", line 601, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python3.8/dist-packages/websocket/_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/usr/local/lib/python3.8/dist-packages/websocket/_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/usr/local/lib/python3.8/dist-packages/websocket/_http.py", line 198, in _open_socket
    raise error
  File "/usr/local/lib/python3.8/dist-packages/websocket/_http.py", line 185, in _open_socket
    sock.connect(address)
OSError: [Errno 99] Cannot assign requested address
2022-05-29 17:19:51,751 - bot - INFO - Bot Started!

**Comment by lzzy12** [comment]
Try `git revert 667bb6e3713372db2425b00d84a6b7272e8f6f0b`

**Comment by mohitjoshi155** [comment]
> Try `git revert 667bb6e3713372db2425b00d84a6b7272e8f6f0b`
fatal bad object 667bb6e3713372db2425b00d84a6b7272e8f6f0b
