### ISSUE TITLE
local deploy 

### ISSUE THREAD

**Issue by YaMraaJ-debug** [lzzy12/python-aria-mirror-bot#264]
Welcome to Cloud Shell! Type "help" to get started.
To set your Cloud Platform project in this session use “gcloud config set project [PROJECT_ID]”
listnavneet007@cs-997902232187-default:~$ c
d mirror-bot
listnavneet007@cs-997902232187-default:~/mirror-bot$ ls
add_to_team_drive.py
app.json
aria.bat
aria.sh
bot
captain-definition
config.env
config_sample.env
credentials.json
Dockerfile
extract
generate_drive_token.py
gen_sa_accounts.py
heroku.yml
LICENSE
pextract
README.md
requirements-cli.txt
requirements.txt
start.sh
token.pickle
vendor
listnavneet007@cs-997902232187-default:~/mirror-bot$ nano config.env
listnavneet007@cs-997902232187-default:~/mirror-bot$ sudo docker build . -t mirror-bot
Sending build context to Docker daemon  55Sending build context to Docker daemon  1.181MB
Step 1/13 : FROM breakdowns/mega-sdk-python:latest
 ---> 3aea64d48f6c
Step 2/13 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 15808613d1a6
Step 3/13 : RUN chmod 777 /usr/src/app
 ---> Using cache
 ---> 2eda630bb1e5
Step 4/13 : COPY requirements.txt .
 ---> Using cache
 ---> 60d50191de39
Step 5/13 : RUN pip3 install --no-cache-dir -r requirements.txt
 ---> Using cache
 ---> d803086477ac
Step 6/13 : COPY extract /usr/local/bin
 ---> Using cache
 ---> 746a70ee2d00
Step 7/13 : COPY pextract /usr/local/bin
 ---> Using cache
 ---> 8196984ae78b
Step 8/13 : RUN chmod +x /usr/local/bin/extract && chmod +x /usr/local/bin/pextract
 ---> Using cache
 ---> f06d5233184b
Step 9/13 : COPY . .
 ---> c244d3e43dd4
Step 10/13 : COPY .netrc /root/.netrc
 ---> 02921effd61b
Step 11/13 : RUN chmod 600 /usr/src/app/.netrc
 ---> Running in 3c03fbfcbcf1
Removing intermediate container 3c03fbfcbcf1
 ---> ce9e39854959
Step 12/13 : RUN chmod +x aria.sh
 ---> Running in 2a905d97640b
Removing intermediate container 2a905d97640b
 ---> 2e4990d46d06
Step 13/13 : CMD ["bash","start.sh"]
 ---> Running in b07d7cc730ba
Removing intermediate container b07d7cc730ba
 ---> 303cdc57dc3b
Successfully built 303cdc57dc3b
Successfully tagged mirror-bot:latest
listnavneet007@cs-997902232187-default:~/mirror-bot$ sudo docker run mirror-bot
2022-08-29 11:37:09,598 - bot - ERROR - connection to server at "ec2-54-157-100-65.compute-1.amazonaws.com" (54.157.100.65), port 5432 failed: FATAL:  password authentication failed for user "zyueovznbxypud"
connection to server at "ec2-54-157-100-65.compute-1.amazonaws.com" (54.157.100.65), port 5432 failed: FATAL:  no pg_hba.conf entry for host "34.87.99.206", user "zyueovznbxypud", database "df9ilghfnq361b", SSL off

Traceback (most recent call last):
  File "/usr/src/app/bot/__init__.py", line 110, in <module>
    conn = psycopg2.connect(DB_URI)
  File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "ec2-54-157-100-65.compute-1.amazonaws.com" (54.157.100.65), port 5432 failed: FATAL:  password authentication failed for user "zyueovznbxypud"
connection to server at "ec2-54-157-100-65.compute-1.amazonaws.com" (54.157.100.65), port 5432 failed: FATAL:  no pg_hba.conf entry for host "34.87.99.206", user "zyueovznbxypud", database "df9ilghfnq361b", SSL off

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/bot/__init__.py", line 124, in <module>
    exit(1)
  File "/usr/lib/python3.8/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 126, in <module>
    cur.close()
NameError: name 'cur' is not defined
listnavneet007@cs-997902232187-default:~/mirror-bot$ 
![Uploading IMG_20220829_012937.jpg…]()

**Comment by shivamdev-lgtm** [comment]
```2022-08-29 11:37:09,598 - bot - ERROR - connection to server at "ec2-54-157-100-65.compute-1.amazonaws.com" (54.157.100.65), port 5432 failed: FATAL: password authentication failed for user "zyueovznbxypud"
connection to server at "ec2-54-157-100-65.compute-1.amazonaws.com" (54.157.100.65), port 5432 failed: FATAL: no pg_hba.conf entry for host "34.87.99.206", user "zyueovznbxypud", database "df9ilghfnq361b", SSL off```
