### ISSUE TITLE
No module named aria2p

### ISSUE THREAD

**Issue by a092devs** [lzzy12/python-aria-mirror-bot#3]
When I run `python3 -m bot` I get this error.

Traceback (most recent call last):                                                                       
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main                                   
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)                                     
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details                                   
    return _get_module_details(pkg_main_name, error)                                                     
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details                                   
    __import__(pkg_name)                                                                                 
  File "/home/ubuntu/mirror-bot/bot/__init__.py", line 3, in <module>                                    
    import aria2p                                                                                        
ModuleNotFoundError: No module named 'aria2p'

**Comment by a092devs** [comment]
> Please read README.md. It contains all the instructions for deploying the bot. And second thing it's python3 -m bot (you're missing 'm')
> @a092devs

I fixed that issue by running `python3 -m pip install -r requirements.txt`.
Now I get different error:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/ubuntu/mirror-bot/bot/__init__.py", line 8, in <module>
    with open('log.txt', 'r+') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'log.txt'

**Comment by lzzy12** [comment]
@a092devs Yes, I will fix it. Till then you can run 
`touch log.txt` command and it should be fixed

**Comment by a092devs** [comment]
> @a092devs Yes, I will fix it. Till then you can run
> `touch log.txt` command and it should be fixed

Thanks, it worked.
