### ISSUE TITLE
Uploads never starts after download

### ISSUE THREAD

**Issue by telegrambotdev** [lzzy12/python-aria-mirror-bot#45]
![Screenshot_2020-02-28-19-44-43-65_5f48d69e3d30a093162f7e0ee7d45862](https://user-images.githubusercontent.com/20116017/75556519-666efa80-5a64-11ea-8251-d970d6c8ef90.png)

small files are uploading.big files get stucked..and doesnt event starts uploading !

**Comment by telegrambotdev** [comment]
2020-02-28T13:50:05.176013+00:00 app[worker.1]: 2020-02-28 13:50:05,175 - bot - INFO - Changed gid from ad80a029c8e7025f to d77dd3326fcf7587
2020-02-28T13:59:34.797873+00:00 app[worker.1]: 2020-02-28 13:59:34,797 - bot - INFO - magnet:?xt=urn:btih:77F21A51EAB0326C6D81593CAAC0A39F3F6D5B4B&dn=T-34.2019.1080p.BluRay.1400MB.DD5.1.x264-GalaxyRG+%E2%AD%90&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fbt.xxx-tracker.com%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce
2020-02-28T13:59:34.811074+00:00 app[worker.1]: 2020-02-28 13:59:34,810 - bot - INFO - Started: ddfd3ff5dddd0c41 DIR:/home/username/mirror-bot/downloads/1649 
2020-02-28T13:59:38.278535+00:00 app[worker.1]: 2020-02-28 13:59:38,278 - bot - INFO - Changed gid from ddfd3ff5dddd0c41 to 60680d312a00d9c2
2020-02-28T14:02:25.600587+00:00 app[worker.1]: 2020-02-28 14:02:25,600 - bot - INFO - Download completed: T-34.2019.1080p.BluRay.1400MB.DD5.1.x264-GalaxyRG[TGx]
2020-02-28T14:02:25.616967+00:00 app[worker.1]: 2020-02-28 14:02:25,616 - bot - INFO - Upload Name : T-34.2019.1080p.BluRay.1400MB.DD5.1.x264-GalaxyRG[TGx]
2020-02-28T14:02:26.250292+00:00 app[worker.1]: 2020-02-28 14:02:26,249 - bot.helper.ext_utils.bot_utils - INFO - Uploading File: /home/username/mirror-bot/downloads/1649/T-34.2019.1080p.BluRay.1400MB.DD5.1.x264-GalaxyRG[TGx]
2020-02-28T14:02:28.179375+00:00 app[worker.1]: 2020-02-28 14:02:28,179 - bot.helper.ext_utils.bot_utils - INFO - Created Google-Drive Folder:
2020-02-28T14:02:28.179388+00:00 app[worker.1]: Name: T-34.2019.1080p.BluRay.1400MB.DD5.1.x264-GalaxyRG[TGx]
2020-02-28T14:02:28.179388+00:00 app[worker.1]: ID: 1-77-6bjwMOSJlenetW8RtVzEfZhaV3pj 
2020-02-28T14:14:27.879205+00:00 app[worker.1]: Exception in thread Thread-3:
2020-02-28T14:14:27.879253+00:00 app[worker.1]: Traceback (most recent call last):
2020-02-28T14:14:27.879255+00:00 app[worker.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 155, in upload
2020-02-28T14:14:27.879255+00:00 app[worker.1]:     result = self.upload_dir(file_path, dir_id)
2020-02-28T14:14:27.879256+00:00 app[worker.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 203, in upload_dir
2020-02-28T14:14:27.879257+00:00 app[worker.1]:     self.upload_file(current_file_name, file_name, mime_type, parent_id)
2020-02-28T14:14:27.879257+00:00 app[worker.1]:   File "/usr/local/lib/python3.6/dist-packages/tenacity/__init__.py", line 311, in wrapped_f
2020-02-28T14:14:27.879257+00:00 app[worker.1]:     return self.call(f, *args, **kw)
2020-02-28T14:14:27.879258+00:00 app[worker.1]:   File "/usr/local/lib/python3.6/dist-packages/tenacity/__init__.py", line 391, in call
2020-02-28T14:14:27.879258+00:00 app[worker.1]:     do = self.iter(retry_state=retry_state)
2020-02-28T14:14:27.879258+00:00 app[worker.1]:   File "/usr/local/lib/python3.6/dist-packages/tenacity/__init__.py", line 338, in iter
2020-02-28T14:14:27.879259+00:00 app[worker.1]:     return fut.result()
2020-02-28T14:14:27.879259+00:00 app[worker.1]:   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
2020-02-28T14:14:27.879260+00:00 app[worker.1]:     return self.__get_result()
2020-02-28T14:14:27.879260+00:00 app[worker.1]:   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
2020-02-28T14:14:27.879260+00:00 app[worker.1]:     raise self._exception
2020-02-28T14:14:27.879260+00:00 app[worker.1]:   File "/usr/local/lib/python3.6/dist-packages/tenacity/__init__.py", line 394, in call
2020-02-28T14:14:27.879261+00:00 app[worker.1]:     result = fn(*args, **kwargs)
2020-02-28T14:14:27.879261+00:00 app[worker.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 121, in upload_file
2020-02-28T14:14:27.879261+00:00 app[worker.1]:     self.status, response = drive_file.next_chunk()
2020-02-28T14:14:27.879262+00:00 app[worker.1]:   File "/usr/local/lib/python3.6/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
2020-02-28T14:14:27.879262+00:00 app[worker.1]:     return wrapped(*args, **kwargs)
2020-02-28T14:14:27.879262+00:00 app[worker.1]:   File "/usr/local/lib/python3.6/dist-packages/googleapiclient/http.py", line 988, in next_chunk
2020-02-28T14:14:27.879262+00:00 app[worker.1]:     headers=headers)
2020-02-28T14:14:27.879262+00:00 app[worker.1]:   File "/usr/local/lib/python3.6/dist-packages/google_auth_httplib2.py", line 198, in request
2020-02-28T14:14:27.879263+00:00 app[worker.1]:     uri, method, body=body, headers=request_headers, **kwargs)
2020-02-28T14:14:27.879263+00:00 app[worker.1]:   File "/usr/local/lib/python3.6/dist-packages/httplib2/__init__.py", line 1991, in request
2020-02-28T14:14:27.879264+00:00 app[worker.1]:     cachekey,
2020-02-28T14:14:27.879264+00:00 app[worker.1]:   File "/usr/local/lib/python3.6/dist-packages/httplib2/__init__.py", line 1690, in _request
2020-02-28T14:14:27.879264+00:00 app[worker.1]:     content,
2020-02-28T14:14:27.879264+00:00 app[worker.1]: httplib2.RedirectMissingLocation: Redirected but the response is missing a Location: header.
2020-02-28T14:14:27.879264+00:00 app[worker.1]: 
2020-02-28T14:14:27.879265+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2020-02-28T14:14:27.879265+00:00 app[worker.1]: 
2020-02-28T14:14:27.879265+00:00 app[worker.1]: Traceback (most recent call last):
2020-02-28T14:14:27.879265+00:00 app[worker.1]:   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
2020-02-28T14:14:27.879266+00:00 app[worker.1]:     self.run()
2020-02-28T14:14:27.879266+00:00 app[worker.1]:   File "/usr/lib/python3.6/threading.py", line 864, in run
2020-02-28T14:14:27.879266+00:00 app[worker.1]:     self._target(*self._args, **self._kwargs)
2020-02-28T14:14:27.879266+00:00 app[worker.1]:   File "/usr/local/lib/python3.6/dist-packages/aria2p/api.py", line 690, in run
2020-02-28T14:14:27.879267+00:00 app[worker.1]:     **{key: closure(value) if key.startswith("on_") else value for key, value in kwargs.items()}
2020-02-28T14:14:27.879267+00:00 app[worker.1]:   File "/usr/local/lib/python3.6/dist-packages/aria2p/client.py", line 1716, in listen_to_notifications
2020-02-28T14:14:27.879267+00:00 app[worker.1]:     callback(notification.gid)
2020-02-28T14:14:27.879267+00:00 app[worker.1]:   File "/usr/local/lib/python3.6/dist-packages/aria2p/api.py", line 686, in <lambda>
2020-02-28T14:14:27.879267+00:00 app[worker.1]:     return (lambda gid: callback(self, gid)) if callable(callback) else None
2020-02-28T14:14:27.879268+00:00 app[worker.1]:   File "/usr/src/app/bot/helper/mirror_utils/download_utils/aria2_download.py", line 35, in __onDownloadComplete
2020-02-28T14:14:27.879268+00:00 app[worker.1]:     self._listener.onDownloadComplete()
2020-02-28T14:14:27.879268+00:00 app[worker.1]:   File "/usr/src/app/bot/modules/mirror.py", line 61, in onDownloadComplete
2020-02-28T14:14:27.879269+00:00 app[worker.1]:     drive.upload(up_name)
2020-02-28T14:14:27.879269+00:00 app[worker.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 161, in upload
2020-02-28T14:14:27.879269+00:00 app[worker.1]:     LOGGER.info(f"Total Attempts: {e.last_attempt.attempt_number}")
2020-02-28T14:14:27.879269+00:00 app[worker.1]: AttributeError: 'RedirectMissingLocation' object has no attribute 'last_attempt'
2020-02-28T14:14:27.879269+00:00 app[worker.1]: 
2020-02-28T14:14:27.879270+00:00 app[worker.1]: 2020-02-28 14:14:27,878 - bot - INFO - Download completed: Terminator Dark Fate (2019) [WEBRip] [720p] [YTS.LT]
2020-02-28T14:14:27.888967+00:00 app[worker.1]: 2020-02-28 14:14:27,888 - bot - INFO - Upload Name : Terminator Dark Fate (2019) [WEBRip] [720p] [YTS.LT]
2020-02-28T14:14:28.324251+00:00 app[worker.1]: 2020-02-28 14:14:28,324 - bot.helper.ext_utils.bot_utils - INFO - Uploading File: /home/username/mirror-bot/downloads/1647/Terminator Dark Fate (2019) [WEBRip] [720p] [YTS.LT]
2020-02-28T14:14:29.803235+00:00 app[worker.1]: 2020-02-28 14:14:29,802 - bot.helper.ext_utils.bot_utils - INFO - Created Google-Drive Folder:
2020-02-28T14:14:29.803252+00:00 app[worker.1]: Name: Terminator Dark Fate (2019) [WEBRip] [720p] [YTS.LT]
2020-02-28T14:14:29.803253+00:00 app[worker.1]: ID: 1b4XjqHPpCiwvs7g0WkIEDMVEFGJsR0nb

**Comment by telegrambotdev** [comment]
![Screenshot_2020-02-28-20-01-14-14_5f48d69e3d30a093162f7e0ee7d45862](https://user-images.githubusercontent.com/20116017/75556923-1b091c00-5a65-11ea-8892-1d21cdeaa8a0.png)


See,small files are uploading.only bigger files have this problem.never starts uploading.

**Comment by a092devs** [comment]
@telegrambotdev Make sure you have this commit 641197b

**Comment by hjyoung1** [comment]
> app[worker.1]

Using heroku? It's not supported anymore
https://github.com/lzzy12/python-aria-mirror-bot/issues/41

**Comment by telegrambotdev** [comment]
> > app[worker.1]
> 
> Using heroku? It's not supported anymore
> #41

i know.but can you identify what is the issue ?

**Comment by lzzy12** [comment]
No support is provided for develop branch. We know it's not working. And that's the reason it's develop.
