### ISSUE TITLE
Error 400 when the file is uploading

### ISSUE THREAD

**Issue by a092devs** [lzzy12/python-aria-mirror-bot#8]
The bot is giving this error when uploading a file.
`HttpError 400 when requesting https://www.googleapis.com/upload/drive/v3/files?alt=json&uploadType=resumable returned "Bad Request"`

Although the file is getting uploaded!

**Comment by lzzy12** [comment]
@a092devs Is that a team drive?

**Comment by a092devs** [comment]
> @a092devs are you uploading to a team drive?

No, I am using my personal drive folder.

**Comment by lzzy12** [comment]
@a092devs Can you invoke /log command and upload the file?

**Comment by a092devs** [comment]
> @a092devs Can you invoke /log command and upload the file sent by bot when this error happens?

Here

`2019-10-30 06:05:34,386 - bot - INFO - Bot Started!
2019-10-30 06:33:15,236 - bot - INFO - Searching: windows
2019-10-30 08:08:48,768 - bot - INFO - Searching: the
2019-10-30 08:08:49,311 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/bot/bot/modules/list.py", line 14, in list_drive
    msg = gdrive.drive_list(search)
  File "/bot/bot/helper/mirror_utils/gdriveTools.py", line 236, in drive_list
    msg += f"⁍ <a href='https://drive.google.com/uc?id={file.get('id')}" \
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-10-30 09:09:52,930 - bot - INFO - magnet:?xt=urn:btih:47805669A83CEF565B601489300871BB73FB3057&dn=ALADDIN.2019.Hindi.1080p.HDTV.AAC.2.0.x264-Telly&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker3.itzmx.com%3A6961%2Fannounce&tr=http%3A%2F%2Ftracker1.itzmx.com%3A8080%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce&tr=udp%3A%2F%2Fdenis.stalker.upeer.me%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.vanitycore.co%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce
2019-10-30 09:09:53,475 - bot - INFO - Adding link: magnet:?xt=urn:btih:47805669A83CEF565B601489300871BB73FB3057&dn=ALADDIN.2019.Hindi.1080p.HDTV.AAC.2.0.x264-Telly&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker3.itzmx.com%3A6961%2Fannounce&tr=http%3A%2F%2Ftracker1.itzmx.com%3A8080%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce&tr=udp%3A%2F%2Fdenis.stalker.upeer.me%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.vanitycore.co%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce
2019-10-30 09:10:03,415 - bot.helper.ext_utils.bot_utils - INFO - [METADATA]ALADDIN.2019.Hindi.1080p.HDTV.AAC.2.0.x264-Telly: Changing GID b868f5e94b22959f to 01a0bdf37996ac58
2019-10-30 09:26:15,024 - bot - INFO - Download completed: Alladin.2019.Hindi.1080p.HDTV.AAC.2.0.x264-Telly
2019-10-30 09:26:15,026 - bot - INFO - Upload Name : Alladin.2019.Hindi.1080p.HDTV.AAC.2.0.x264-Telly
2019-10-30 09:26:15,201 - bot.helper.ext_utils.bot_utils - INFO - Uploading File: Alladin.2019.Hindi.1080p.HDTV.AAC.2.0.x264-Telly
2019-10-30 09:26:15,204 - bot.helper.ext_utils.bot_utils - INFO - status: None
2019-10-30 09:26:17,363 - bot.helper.ext_utils.bot_utils - INFO - Created Google-Drive Folder:
Name: Alladin.2019.Hindi.1080p.HDTV.AAC.2.0.x264-Telly
ID: 1zqEPLas8-dYtAnbpXdHTX3U4QW12eoCB 
2019-10-30 09:26:17,590 - bot.helper.ext_utils.bot_utils - ERROR - <HttpError 400 when requesting https://www.googleapis.com/upload/drive/v3/files?alt=json&uploadType=resumable returned "Bad Request">
2019-10-30 09:26:17,590 - bot - ERROR - HttpError 400 when requesting https://www.googleapis.com/upload/drive/v3/files?alt=json&uploadType=resumable returned "Bad Request"
2019-10-30 09:26:17,810 - bot - INFO - Cleaning download: /app/downloads/173`

**Comment by a092devs** [comment]
> @a092devs Can you invoke /log command and upload the file sent by bot when this error happens?

Here
`2019-10-30 06:05:34,386 - bot - INFO - Bot Started!
2019-10-30 06:33:15,236 - bot - INFO - Searching: windows
2019-10-30 08:08:48,768 - bot - INFO - Searching: the
2019-10-30 08:08:49,311 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/bot/bot/modules/list.py", line 14, in list_drive
    msg = gdrive.drive_list(search)
  File "/bot/bot/helper/mirror_utils/gdriveTools.py", line 236, in drive_list
    msg += f"⁍ <a href='https://drive.google.com/uc?id={file.get('id')}" \
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-10-30 09:09:52,930 - bot - INFO - magnet:?xt=urn:btih:47805669A83CEF565B601489300871BB73FB3057&dn=ALADDIN.2019.Hindi.1080p.HDTV.AAC.2.0.x264-Telly&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker3.itzmx.com%3A6961%2Fannounce&tr=http%3A%2F%2Ftracker1.itzmx.com%3A8080%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce&tr=udp%3A%2F%2Fdenis.stalker.upeer.me%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.vanitycore.co%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce
2019-10-30 09:09:53,475 - bot - INFO - Adding link: magnet:?xt=urn:btih:47805669A83CEF565B601489300871BB73FB3057&dn=ALADDIN.2019.Hindi.1080p.HDTV.AAC.2.0.x264-Telly&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker3.itzmx.com%3A6961%2Fannounce&tr=http%3A%2F%2Ftracker1.itzmx.com%3A8080%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce&tr=udp%3A%2F%2Fdenis.stalker.upeer.me%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.vanitycore.co%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce
2019-10-30 09:10:03,415 - bot.helper.ext_utils.bot_utils - INFO - [METADATA]ALADDIN.2019.Hindi.1080p.HDTV.AAC.2.0.x264-Telly: Changing GID b868f5e94b22959f to 01a0bdf37996ac58
2019-10-30 09:26:15,024 - bot - INFO - Download completed: Alladin.2019.Hindi.1080p.HDTV.AAC.2.0.x264-Telly
2019-10-30 09:26:15,026 - bot - INFO - Upload Name : Alladin.2019.Hindi.1080p.HDTV.AAC.2.0.x264-Telly
2019-10-30 09:26:15,201 - bot.helper.ext_utils.bot_utils - INFO - Uploading File: Alladin.2019.Hindi.1080p.HDTV.AAC.2.0.x264-Telly
2019-10-30 09:26:15,204 - bot.helper.ext_utils.bot_utils - INFO - status: None
2019-10-30 09:26:17,363 - bot.helper.ext_utils.bot_utils - INFO - Created Google-Drive Folder:
Name: Alladin.2019.Hindi.1080p.HDTV.AAC.2.0.x264-Telly
ID: 1zqEPLas8-dYtAnbpXdHTX3U4QW12eoCB 
2019-10-30 09:26:17,590 - bot.helper.ext_utils.bot_utils - ERROR - <HttpError 400 when requesting https://www.googleapis.com/upload/drive/v3/files?alt=json&uploadType=resumable returned "Bad Request">
2019-10-30 09:26:17,590 - bot - ERROR - HttpError 400 when requesting https://www.googleapis.com/upload/drive/v3/files?alt=json&uploadType=resumable returned "Bad Request"
2019-10-30 09:26:17,810 - bot - INFO - Cleaning download: /app/downloads/173`

**Comment by a092devs** [comment]
@lzzy12 one more query, suppose I want to change /mirror to some customized /command, where can i do that?
I am guessing helper/tg_helper/bot_commands.py
helpful if there is more than one bot in the group.

**Comment by lzzy12** [comment]
@a092devs Yep you got it. Just change the values in quotes

**Comment by a092devs** [comment]
@lzzy12 ok ok, take your time.
